name: Discord Webhook

on:
  push:
    branches:
      - main

jobs:
  send_discord_notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get last commit message
      id: get_last_commit_message
      run: |
        cd ${{ github.workspace }}  # Se déplacer dans le répertoire du référentiel
        LAST_COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
        echo "::set-output name=last_commit_message::$LAST_COMMIT_MESSAGE"

    - name: Send Discord Notification
      run: |
        COMMIT_MESSAGE="${{ steps.get_last_commit_message.outputs.last_commit_message }}"
        curl -X POST -H "Content-Type: application/json" -d '{
          "content": "Ambre",
          "embeds": [
            {
              "title": "Mise à jour",
              "description": "https://gabryel666.github.io/Ambre/book/index.html",
              "color": 16776960,
              "fields": [
                {
                  "name": "Dernier commit",
                  "value": "'"$COMMIT_MESSAGE"'"
                }
              ]
            }
          ]
        }' ${{ secrets.DISCORD_WEBHOOK_URL }}
